services:
  server:
    image: ${DOCKER_USERNAME}/backend:${IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - AWS_REGION=${AWS_REGION}
      - MONGO_URI=${MONGO_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped
    volumes:
      - /home/${{ secrets.EC2_USER }}/Bookstore/uploads:/app/uploads  # Store uploads in EC2 filesystem

volumes:
  mongodb_data:
