services:
  server:
    image: ${DOCKER_USERNAME}/backend:${IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - AWS_REGION=${{secrets.AWS_REGION}}
      - MONGO_URI=${{secrets.MONGO_URI}}
      - AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
    restart: unless-stopped
    volumes:
      - /home/${{ secrets.EC2_USER }}/Bookstore/uploads:/uploads

volumes:
  mongodb_data:
