services:
  server:
    image: ${DOCKER_USERNAME}/backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - AWS_REGION=${AWS_REGION}
      - MONGO_URI=${MONGO_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped
    volumes:
      - /home/${EC2_USER}/Bookstore/uploads:/home/${EC2_USER}/Bookstore/uploads

volumes:
  mongodb_data:
